name: buildNumberTest
on: 
  workflow_dispatch:
    inputs:
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest    
    env: 
     PROVAR_HOME: ${{ github.workspace }}/ProvarHome
    strategy:
      fail-fast: false
      matrix:
        Plan: ["Test1","Test2","Test3"]
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
        
    - name: BuildName1
      run:  echo ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
    - name: BuildName2
      run:  echo ${{ github.run_id }}-${{ github.run_number }}

    - name: Upload Report To Slack
      uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       title: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
       token: ${{ secrets.SLACK_TOKEN }}
    
    - uses: actions/upload-artifact@v2
      with:
        name: Execution Report for ${{matrix.Plan}}- ${{ steps.date.outputs.date }}
        path: ${{ github.workspace }}/ANT/Results/*
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Execution Report for ${{matrix.Plan}}- ${{ steps.date.outputs.date }}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        path: ${{ github.workspace }}/ANT/Results/*    
