name: FianlTry1

on: 
  workflow_dispatch:
    inputs:
      plan:
        description: 'Enter Plan Name'
        required: true
    
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
  
jobs:
  build:

    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
    
    steps:
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H_%M_%S')"
                                         
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: 8
    
     
    - name: Upload test file
      uses: actions/checkout@v1
    - run: echo "Execution Started for Test Plan ${{github.event.inputs.plan}} at ${{ steps.date.outputs.date }}"> ExecutionStarted.txt
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: ExecutionStarted.txt
          channel: provar-gitaction
  
    - name: Execute Test Plan
      run: |
        mkdir $GITHUB_WORKSPACE/ProvarHome
        curl -O Provar_ANT_latest.zip https://download.provartesting.com/latest/Provar_ANT_latest.zip
        unzip -o Provar_ANT* -d ProvarHome
        rm Provar_ANT_*
        sudo apt-get update && sudo apt-get upgrade       
        wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -        
        sudo echo "deb [arch=amd64]  http://dl.google.com/linux/chrome/deb/ stable main" >>sudo tee -a /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get -y install google-chrome-stable
        echo $PROVAR_HOME
        cd $GITHUB_WORKSPACE/ANT
        echo "Selected Plan Name="${{ github.event.inputs.plan }}
        echo "Selected Environment is="${{ github.event.inputs.TestEnv }}
        xvfb-run ant -file build.xml "-DTestEnv=${{ github.event.inputs.TestEnv }}" "-DTestPlan=${{ github.event.inputs.plan }}" runtests
        zip -v -r Execution_Report_for_${{github.workflow}}_${{github.event.inputs.plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}.zip Results/*
        echo "List of file"
        ls -a
    
    - uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       token: ${{ secrets.SLACK_TOKEN }}
       path: ${{ github.workspace }}/ANT/Results/JUnit html/junit-noframes.html
       channel: provar-gitaction
       title: JUnit Report

    - name: Upload Report To Slack
      if: ${{ always() }}
      run: |
        echo "Working Directory"
        pwd
        cd $GITHUB_WORKSPACE/ANT
        ls -a
        zip -v -r Execution_Report_for_${{github.workflow}}_${{github.event.inputs.plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}.zip Results/*
        echo "List of file"
        ls -a
        
    - uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       token: ${{ secrets.SLACK_TOKEN }}
       path: ${{ github.workspace }}/ANT/Execution_Report_for_${{github.workflow}}_${{github.event.inputs.plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}.zip
       channel: provar-gitaction   
       
    - uses: actions/upload-artifact@v2
      with:
        name: Execution_Report_for_${{github.workflow}}_${{github.event.inputs.plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}
        path: ${{ github.workspace }}/ANT/Results/*
    
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Execution_Report_for_${{github.workflow}}_${{github.event.inputs.plan}}-${{ steps.date.outputs.date }}_${{github.run_attempt}}-${{job.status}}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        path: ${{ github.workspace }}/ANT/Results/*
