name: slack-notification-with-optional-parameters

on: 
  workflow_dispatch:
    inputs:
      
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 

jobs:
  slack-notification-with-optional-parameters:
    runs-on: ubuntu-20.04
    name: Sends a message to Slack when a push, a pull request or an issue is made
    steps:
      - name: Send message to Slack API
        uses: archive/github-actions-slack@v2.0.0
        id: notify
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_TOKEN }}
          slack-channel: C03KF4U7TSP 
          slack-text: Hello! Something is burning! Or not...
          slack-optional-icon_emoji: ":fire:"
          slack-optional-as_user: false
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
