name: temp

on: 
  workflow_dispatch:
    inputs:
      plan:
        type: choice
        description: Please select Test Plan For the execution
        options: 
        - Temp
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
  
jobs:
  build:

    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
    
    steps:
    - name: Build with Ant
      run: |
        mkdir $GITHUB_WORKSPACE/ANT/Results/
        echo "Test file " > $GITHUB_WORKSPACE/ANT/Results/test.txt
    - uses: actions/upload-artifact@v2
      with:
        name: Execution Report for ${{ github.event.inputs.plan }}- ${{ steps.date.outputs.date }}
        path: ${{ github.workspace }}/ANT/Results/*
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: Execution Report for ${{ github.event.inputs.plan }}- ${{ steps.date.outputs.date }}                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             
        path: ${{ github.workspace }}/ANT/Results/*
    - name: Upload Report To Slack
      uses: adrey/slack-file-upload-action@master
      if: ${{ always() }}
      with:
       run: zip -r
       token: ${{ secrets.SLACK_TOKEN }}
       path: ${{ github.workspace }}/ANT/Results/*
       channel: provar-gitaction
    
