name: temp

on: 
  workflow_dispatch:
    inputs:
      plan:
        type: choice
        description: Please select Test Plan For the execution
        options: 
        - Temp
      TestEnv:
        type: choice
        description: Please select environment
        options: 
        - AutomationOrg 
  
jobs:
  build:

    runs-on: ubuntu-latest
    env: 
       PROVAR_HOME: ${{ github.workspace }}/ProvarHome
    
    steps:
    - name: Build with Ant
      run: |
        
        echo "Test file " > ${{ github.workspace }}/ANT/Results/test.txt
 
   
    - name: Checkout
      uses: actions/checkout@v1
    - run: echo "Test file " > test123.txt
    - name: Upload to slack step
      uses: adrey/slack-file-upload-action@master
      with:
          token: ${{ secrets.SLACK_TOKEN }}
          path: ${{ github.workspace }}/ANT/Results/test.txt
          channel: provar-gitaction
    
